### ISSUE TITLE
注意区别解约和违约

### ISSUE THREAD

**Issue by wujiechn** [foreverblog/admin#11]
既然在申请时，写明白了可以自由退出，那么就应该有解约的选项，解约不等于异常，也不等于违约，约定都解除了，何来违约一说？

我解约了，就说明我不想在成员页面显示我的博客了，但是现在进入异常名单，还是仍然能显示，解约并退出的意义何在？

网站异常的属于单方面违约，异常名单可以展示，这算是一种处罚？（鞭尸）。今天在QQ群讨论，管理员说计划后面加个退出名单，其实我是觉得没必要的，退出了就不要再展示了，展示了也无意义，既然你要展示，和我没退出之前有什么区别？我就是出于不想展示，才退出的。

今天体验了一下你们所谓的“自由退出”，但是体验非常糟糕。

希望能处理好这部分的用户体验，而不是让用户感觉“进来容易出去难”，随着用项目的发展，这是必须要面对的问题，即便我今天不提，后面也会有别人提。

**Comment by sy-records** [comment]
十年之约作为一个自愿加入的活动，你既然申请加入并且已经公示在成员页面了，那么申请退出就是相当于“异常”，会标记异常，在公约中也有说明：

> 在必要的情况下，您可自由退出“十年之约”，但退出前需向项目组提交申请说明退出理由
